version: '3'

services:

  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-notebook
    user: root

    ports:
      - "8888:8888"
      - "4040:4040"
      - "8503:8503"

    environment:
      - JUPYTER_ENABLE_LAB=yes

    volumes:
      - ../:/work

    command: start-notebook.sh --NotebookApp.token=''